RM_INCH = 225
RM_LETTER_WIDTH = int(RM_INCH * 8.5)
RM_LETTER_HEIGHT = int(RM_INCH * 11)

OUTPUT_DIRECTORY = "output"
TEMP_DIRECTORY = "temp"
CONFIG_DIRECTORY = "config"
BIN_DIRECTORY = "bin"

DIRECTORIES = [OUTPUT_DIRECTORY, TEMP_DIRECTORY, CONFIG_DIRECTORY, BIN_DIRECTORY]

